trigger:
  branches:
    include:
    - dev
    - release-*
pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:
- job: Windows
  strategy:
    matrix:
      VS2017:
        imageName: 'vs2017-win2016'
        TILEDB_S3: ON
  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/azure-windows.yml
